# Generated by Django 6.0.2 on 2026-02-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='Task ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='Task Name')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Result')),
            ],
            options={
                'verbose_name': 'Task Metadata',
                'verbose_name_plural': 'Tasks Metadata',
            },
        ),
    ]
